<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="29542" started-at="2020-06-02T11:07:15Z" finished-at="2020-06-02T11:07:45Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="29542" started-at="2020-06-02T11:07:15Z" finished-at="2020-06-02T11:07:45Z">
      <class name="ER.ER.EReport2">
        <test-method status="PASS" signature="testGoogle()[pri:0, instance:ER.ER.EReport2@1500955a]" name="testGoogle" duration-ms="14971" started-at="2020-06-02T11:07:15Z" finished-at="2020-06-02T11:07:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGoogle -->
      </class> <!-- ER.ER.EReport2 -->
      <class name="ER.ER.EReport1">
        <test-method status="PASS" signature="testYouTube()[pri:0, instance:ER.ER.EReport1@26a7b76d]" name="testYouTube" duration-ms="29484" started-at="2020-06-02T11:07:15Z" finished-at="2020-06-02T11:07:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testYouTube -->
      </class> <!-- ER.ER.EReport1 -->
      <class name="ER.ER.EReport3">
        <test-method status="FAIL" signature="testYahoo()[pri:0, instance:ER.ER.EReport3@e874448]" name="testYahoo" duration-ms="18812" started-at="2020-06-02T11:07:15Z" finished-at="2020-06-02T11:07:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at ER.ER.EReport3.testYahoo(EReport3.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testYahoo -->
      </class> <!-- ER.ER.EReport3 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
